export const TEAM = [
  { name: "Jeff", face: "/img/jeff.png" },
  { name: "Brian", face: "/img/brian.png" },
  { name: "Daryl", face: "/img/daryl.png" },
  { name: "Jean", face: "/img/jean.png" },
  { name: "Jess", face: "/img/jess.png" },
  { name: "Jiefry", face: "/img/jiefry.png" },
  { name: "Jl", face: "/img/jl.png" },
  { name: "Jon", face: "/img/jon.png" },
  { name: "Juan Manuel", face: "/img/juan-manuel.png" },
  { name: "Kathleen", face: "/img/kathleen.png" },
  { name: "Kev", face: "/img/kev.png" },
  { name: "Matthew", face: "/img/matthew.png" },
  { name: "Muskan", face: "/img/muskan.png" },
  { name: "Raunak", face: "/img/raunak.png" },
  { name: "Steve", face: "/img/steve.png" },
  { name: "Tina", face: "/img/tina.png" },
];
