export const TEAM = [
  { name: "Jeff", face: "/img/jeff.png" },
  { name: "Brian", face: "/img/brian.png" },
  { name: "Daryl", face: "/img/daryl.png" },
  { name: "Jess", face: "/img/jess.png" },
  { name: "Jiefry", face: "/img/jiefry.png" },
  { name: "Jl", face: "/img/jl.png" },
  { name: "Jon", face: "/img/jon.png" },
  { name: "Kathleen", face: "/img/kathleen.png" },
  { name: "Kev", face: "/img/kev.png" },
  { name: "Muskan", face: "/img/muskan.png" },
  { name: "Steve", face: "/img/steve.png" },
  { name: "Tina", face: "/img/tina.png" },
  { name: "Louis", face: "/img/louis.png" },
  { name: "Mark", face: "/img/mark.png" },
  { name: "Jordan", face: "/img/jordan.png" },
  { name: "Jasper", face: "/img/jasper.png" },
];
